cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart-summery"),
    path("session/add-prod/", views.AddProdView.as_view(), name="add-prod"),
    path("session/del-prod/", views.DelProdView.as_view(), name="del-prod"),
    path("session/clear/", views.ClearView.as_view(), name="clear"),
    path(
        "session/change-prod-quantity/",
        views.ChangeProdQuantityView.as_view(),
        name="change-prod-quantity",
    ),
]

core/urls.py
from itertools import product
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from shop.sitemaps import ProductSitemap

sitemaps = {"static": StaticViewSitemap, "products": ProductSitemap}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("website.urls")),
    path("accounts/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("cart/", include("cart.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
    path("review/", include("review.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

handler404 = "core.error_views.error_404"

if settings.DEBUG:
    import debug_toolbar
    from rest_framework import permissions
    from drf_yasg.views import get_schema_view
    from drf_yasg import openapi

    schema_view = get_schema_view(
        openapi.Info(
            title="Django Online Shop API",
            default_version="v1",
            description="you can use it by any front end framework like (React, Vue, Angular, ...)",
            terms_of_service="https://www.google.com/policies/terms/",
            contact=openapi.Contact(email="benxfoxy@gmail.com"),
            license=openapi.License(name="MIT License"),
        ),
        public=True,
        permission_classes=(permissions.AllowAny,),
    )

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
        path(
            "swagger<format>/",
            schema_view.without_ui(cache_timeout=0),
            name="schema-json",
        ),
        path(
            "swagger/",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
    ]

    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path("checkout/", views.CheckOutView.as_view(), name="checkout"),
    path("check/", views.CheckView.as_view(), name="check"),
    path("complete/", views.OrderCompleteView.as_view(), name="complete"),
    path("faild/", views.OrderFaildView.as_view(), name="faild"),
]

shop/urls.py
from django.urls import include, path, re_path
from . import views

app_name = "shop"

urlpatterns = [
    path(
        "product/list/grid/",
        views.ShopProductGridListView.as_view(),
        name="list_grid",
    ),
    path("product/list/", views.ShopProductListView.as_view(), name="list"),
    re_path(
        r"product/(?P<slug>[-\w]+)/detail/",
        views.ShopProductDetailView.as_view(),
        name="detail",
    ),
    path(
        "product/add-or-remove-wish/",
        views.AddOrRemoveWish.as_view(),
        name="modify-wish",
    ),
    # Shop API section
    path("api/v1/", include("shop.api.urls")),
]

website/urls.py
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path("", views.IndexView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
]

cart/models.py
from django.db import models


# Create your models here.
class CartModel(models.Model):
    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email

    def calculate_total_price(self):
        return sum(
            prod.product.offer() * prod.quantity
            for prod in self.cart_items.all()
        )


class CartItemModel(models.Model):
    cart = models.ForeignKey(
        CartModel, on_delete=models.CASCADE, related_name="cart_items"
    )
    product = models.ForeignKey("shop.ProductModel", on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=0)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product.title} - {self.cart.id}"

cart/views.py
from django.views.generic import View, TemplateView
from django.http import JsonResponse
from .cart import CartSession


class AddProdView(View):
    def post(self, request, *args, **kwargs):
        cart = CartSession(request.session)
        if product_id := request.POST.get("product_id"):
            cart.add_prod(product_id)
        if request.user.is_authenticated:
            cart.cart_merge(request.user)
        return JsonResponse(
            {
                "cart": cart.get_cart(),
                "total_quantity": cart.get_cart_quantity(),
                "message": "Product added to cart!!"

            }
        )


class DelProdView(View):
    def post(self, request, *args, **kwargs):
        cart = CartSession(request.session)
        if product_id := request.POST.get("product_id"):
            cart.del_prod(product_id)
        if request.user.is_authenticated:
            cart.cart_merge(request.user)
        return JsonResponse(
            {
                "cart": cart.get_cart(),
                "total_quantity": cart.get_cart_quantity(),
            }
        )


class ChangeProdQuantityView(View):
    def post(self, request, *args, **kwargs):
        cart = CartSession(request.session)
        product_id = request.POST.get("product_id")
        quantity = request.POST.get("quantity")
        if product_id and quantity:
            cart.change_prod_quantity(product_id, quantity)
        if request.user.is_authenticated:
            cart.cart_merge(request.user)
        return JsonResponse(
            {
                "cart": cart.get_cart(),
                "total_quantity": cart.get_cart_quantity(),
            }
        )


class CartView(TemplateView):
    template_name = "cart/cart.html"

    def get_template_names(self):
        cart = CartSession(self.request.session)
        if not cart.get_cart_items():
            return ["cart/empty-cart.html"]
        return super().get_template_names()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = CartSession(self.request.session)
        context["cart_items"] = cart.get_cart_items()
        context["total_quantity"] = cart.get_cart_quantity()
        context["total_price"] = cart.get_total_price()

        return context


class ClearView(View):
    def post(self, request, *args, **kwargs):
        cart = CartSession(request.session)
        cart.clear()
        if request.user.is_authenticated:
            cart.cart_merge(request.user)
        return JsonResponse({"cart": cart.get_cart()})

templates/cart/cart.html
{% extends "base.html" %} 
{% load static %} 
<title>{% block title %}Yoogi | cart {% endblock title %}</title>  
{% load humanize %} 
{% block content %}
<!-- ========== MAIN CONTENT ========== -->
<div class="container content-space-1 content-space-lg-2">
  <div class="row">
    <div class="col-lg-8 mb-7 mb-lg-0">
      <!-- Heading -->
      <div class="d-flex justify-content-between align-items-end border-bottom pb-3 mb-7">
        <h1 class="h3 mb-0">Shopping Cart</h1>
        <span>{{total_quantity}} Items</span>
      </div>
      <!-- End Heading -->
      
      <!-- Form -->
      <form>
        <!-- List Group -->
        <ul class="list-group list-group-flush list-group-no-gutters mb-5">
          <!-- Item -->
          {% for prod in cart_items %}
          <li class="list-group-item">
            <div class="d-flex">
              <div class="flex-shrink-0">
                <img
                  class="avatar avatar-xl avatar-4x3"
                  src="{{ prod.prod_obj.product_image_related.all.first.image.url }}"
                  alt="Image Description"
                />
              </div>
              <div class="flex-grow-1 ms-3">
                <div class="row">
                  <div class="col-sm-7 mb-3 mb-sm-0">
                    <h5>
                      <a class="text-dark" href="{% url 'shop:detail' slug=prod.prod_obj.slug %}">{{prod.prod_obj.title}}</a>
                    </h5>                      
                    <div class="d-grid gap-1">
                      <div class="text-body">
                        <span class="small">Category:</span>
                        <span class="fw-semibold small">
                          {% for cat in prod.prod_obj.category.all %}
                          {{cat}}
                          {% if not forloop.last %}, {% endif %}
                          {% endfor %}
                        </span>
                      </div>
                    </div>
                  </div>
                  <!-- End Col -->

                  <div class="col-sm-3">
                    <div class="row">
                      <div class="col-auto">
                        <!-- Select -->
                        <select class="form-select form-select-sm mb-3"
                          onchange="changeprodquantity(`{{ prod.product_id }}`,this.value)">
                          {% with ''|center:prod.prod_obj.stock as range %}
                          {% for _ in range %}
                          <option value="{{ forloop.counter }}"
                            {% if forloop.counter == prod.quantity %} selected {% endif %}>
                            {{ forloop.counter }}
                          </option>
                          {% endfor %}
                          {% endwith %}
                        </select>
                        <!-- End Select -->
                      </div>

                      <div class="col-auto">
                        <div class="d-grid gap-2 d-flex justify-content-between">
                          <button class="btn btn-sm btn-icon text-danger border-0 mx-1" onclick="delprod(`{{ prod.product_id }}`)">
                            <i class="bi-trash ms-1"></i> Remove
                          </button>
                        </div>
                      </div>
                      <!-- End Col -->
                    </div>
                    <!-- End Row -->
                  </div>
                  <!-- End Col -->

                  <div class="col-4 col-sm-2 d-none d-sm-inline-block text-right">
                    {% if prod.prod_obj.discount_percent %}
                    <span class="text-body ms-1"><del>{{prod.prod_obj.price|intcomma}}</del></span>
                    {% endif %}
                    <span class="h5 d-block mb-1">{{prod.prod_obj.offer|intcomma}}</span>
                    <p>KES</p>
                  </div>
                  <!-- End Col -->
                </div>
                <!-- End Row -->
              </div>
            </div>
          </li>
          {% endfor %}
          <!-- End Item -->
        </ul>
        <!-- End List Group -->

        <div class="d-sm-flex justify-content-end">
          <a class="link" href="{% url 'shop:list_grid' %}">
            Continue Shopping <i class="bi-chevron-left small ms-1"></i>
          </a>
        </div>
      </form>
      <!-- End Form -->
    </div>
    <!-- End Col -->

    <div class="col-lg-4">
      <div class="ps-lg-4">
        <!-- Card -->
        <div class="card card-sm shadow-sm mb-4">
          <div class="card-body">
            <div class="border-bottom pb-4 mb-4">
              <h3 class="card-header-title">Summary</h3>
            </div>
            <form>
              <div class="d-grid gap-3 mb-4">
                <dl class="row">
                  <dt class="col-sm-6">Tax</dt>
                  <dd class="col-sm-12 text-sm-end mb-0">
                    Including 9% at checkout
                  </dd>
                </dl>
                <!-- End Row -->
                
                <dl class="row">
                  <dt class="col-sm-6">Total</dt>
                  <dd class="col-sm-12 text-sm-end mb-0">{{total_price|intcomma}} KES</dd>
                </dl>
                <!-- End Row -->
              </div>
              
              <div class="d-grid" style="margin-bottom: 10px;">
                <a class="btn btn-primary btn-lg" href="{% url 'order:checkout' %}">Place Order</a>
              </div>
              <div class="d-grid">
                <button class="btn btn-danger btn-lg" onclick="clearProducts()">Clear Cart</button>
              </div>
            </form>
          </div>
          <!-- End Card -->
        </div>

        <!-- Media -->
        <div class="d-flex align-items-center">
          <div class="flex-shrink-0">
            <div class="svg-icon svg-icon-sm text-primary">
              <!-- SVG ICON HERE -->
            </div>
          </div>
          <div class="flex-grow-1 ms-2">
            <span class="small me-1">Do you need support?</span>
            <a class="link small" href="{% url 'website:contact' %}">Submit a ticket.</a>
          </div>
        </div>
        <!-- End Media -->
      </div>
    </div>
    <!-- End Col -->
  </div>
  <!-- End Row -->
</div>
{% endblock content %}

{% block extera-js %}
  
<!-- JS Implementing Plugins -->
<script src="{% static '/js/vendor.min.js' %}"></script>

<!-- JS Front -->
<script src="{% static '/js/theme.min.js' %}"></script>

<!-- JS Plugins Init. -->
<script>
  (function () {
    // INITIALIZATION OF MEGA MENU
    // =======================================================
    new HSMegaMenu(".js-mega-menu", {
      desktop: {
        position: "left",
      },
    });

    // INITIALIZATION OF SHOW ANIMATIONS
    // =======================================================
    new HSShowAnimation(".js-animation-link");

    // INITIALIZATION OF BOOTSTRAP VALIDATION
    // =======================================================
    HSBsValidation.init(".js-validate", {
      onSubmit: (data) => {
        data.event.preventDefault();
        alert("Submited");
      },
    });

    // INITIALIZATION OF BOOTSTRAP DROPDOWN
    // =======================================================
    HSBsDropdown.init();

    // INITIALIZATION OF GO TO
    // =======================================================
    new HSGoTo(".js-go-to");
  })();
</script>

<script>
  function delprod(product_id) {
    $.ajax({
    type: "POST",
    url: "{% url 'cart:del-prod' %}",
    data: {
      'product_id': product_id,
      csrfmiddlewaretoken: '{{ csrf_token }}',
    },
    success: function(response){
      console.log(response)
      window.location.reload();
    },
    error: function(jqXHR,textStatus,errorThrown) {
      console.log(response)
    }
  });
  }

  function changeprodquantity(product_id,quantity) {
    $.ajax({
    type: "POST",
    url: "{% url 'cart:change-prod-quantity' %}",
    data: {
      'product_id': product_id,
      'quantity': quantity,
      csrfmiddlewaretoken: '{{ csrf_token }}',
    },
    success: function(response){
      console.log(response)
      window.location.reload();
    },
    error: function(jqXHR,textStatus,errorThrown) {
      console.log(response)
    }
  });
  }
  function clearProducts() {
    $.ajax({
    type: "POST",
    url: "{% url 'cart:clear' %}",
    data: {
      csrfmiddlewaretoken: '{{ csrf_token }}',
    },
    success: function(response){
      console.log(response)
      window.location.reload();
    },
    error: function(jqXHR,textStatus,errorThrown) {
      console.log(response)
    }
  });
  }
</script>
{% endblock extera-js %}

templates/cart/empty-cart.html
{% extends "base.html" %}
{% load static %}
<title>{% block title %}Yoogi | cart {% endblock title %}</title>  

{% block content %}
  
<div class="container content-space-2 content-space-lg-3">
    <div class="w-md-75 w-lg-50 text-center mx-md-auto">
      <div class="mb-5">
        <img class="img-fluid" src="{% static 'svg/illustrations/oc-empty-cart.svg' %}" alt="Image Description" style="width: 15rem;">
      </div>

      <div class="mb-5">
        <h1 class="h2">Your cart is currently empty</h1>
        <p>Before proceeding to checkout, you need to add products to your cart. You will find many interesting products on our "Shop" page.</p>
      </div>

      <a class="btn btn-primary btn-transition rounded-pill px-6" href="{% url 'shop:list_grid' %}">Start Shopping</a>
    </div>
  </div>

{% endblock content %}