cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart-summery"),
    path("session/add-prod/", views.AddProdView.as_view(), name="add-prod"),
    path("session/del-prod/", views.DelProdView.as_view(), name="del-prod"),
    path("session/clear/", views.ClearView.as_view(), name="clear"),
    path(
        "session/change-prod-quantity/",
        views.ChangeProdQuantityView.as_view(),
        name="change-prod-quantity",
    ),
]

core/urls.py
from itertools import product
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from shop.sitemaps import ProductSitemap

sitemaps = {"static": StaticViewSitemap, "products": ProductSitemap}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("website.urls")),
    path("accounts/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("cart/", include("cart.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
    path("review/", include("review.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

handler404 = "core.error_views.error_404"

if settings.DEBUG:
    import debug_toolbar
    from rest_framework import permissions
    from drf_yasg.views import get_schema_view
    from drf_yasg import openapi

    schema_view = get_schema_view(
        openapi.Info(
            title="Django Online Shop API",
            default_version="v1",
            description="you can use it by any front end framework like (React, Vue, Angular, ...)",
            terms_of_service="https://www.google.com/policies/terms/",
            contact=openapi.Contact(email="benxfoxy@gmail.com"),
            license=openapi.License(name="MIT License"),
        ),
        public=True,
        permission_classes=(permissions.AllowAny,),
    )

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
        path(
            "swagger<format>/",
            schema_view.without_ui(cache_timeout=0),
            name="schema-json",
        ),
        path(
            "swagger/",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
    ]

    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

dashboard/urls.py
from django.urls import path, include
from . import views

app_name = "dashboard"

urlpatterns = [
    path("check/", views.DashboardCheckView.as_view(), name="check"),
    path("admin/", include("dashboard.admin.urls")),
    path("customer/", include("dashboard.customer.urls")),
    path(
        "profile/edit/", views.ProfileEditView.as_view(), name="profile-edit"
    ),
]

dashboard/admin/forms/member.py
from django import forms
from accounts.models import User


class AdminMemberEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "is_active",
            "is_verified",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["is_active"].widget.attrs["class"] = "form-check-input"
        self.fields["is_verified"].widget.attrs["class"] = "form-check-input"

dashboard/admin/views/coupon.py
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import FieldError
from ...permissions import AdminPermissions
from ..forms import AdminCouponForm
from order.models import CouponModel
from ..forms import *
from django.db.models import Count, F


class AdminCouponView(LoginRequiredMixin, AdminPermissions, ListView):
    template_name = "dashboard/admin/coupons/coupon-list.html"
    context_object_name = "coupons"

    paginate_by = 10

    def get_paginate_by(self, queryset):
        return self.request.GET.get("page_size", self.paginate_by)

    def get_queryset(self):
        queryset = CouponModel.objects.all()
        if search_q := self.request.GET.get("q"):
            queryset = queryset.filter(code__icontains=search_q)
        if category_id := self.request.GET.get("category_id"):
            if category_id == "1":
                queryset = queryset.annotate(
                    used_count=Count("used_by")
                ).exclude(max_limit_usage=F("used_count"))
            elif category_id == "2":
                queryset = queryset.annotate(
                    used_count=Count("used_by")
                ).filter(max_limit_usage=F("used_count"))
        if order_by := self.request.GET.get("order_by"):
            try:
                queryset = queryset.order_by(order_by)
            except FieldError:
                pass
        return queryset


class AdminCouponCreateView(
    LoginRequiredMixin, AdminPermissions, CreateView, SuccessMessageMixin
):
    queryset = CouponModel.objects.all()
    template_name = "dashboard/admin/coupons/coupon-create.html"
    form_class = AdminCouponForm
    success_url = reverse_lazy("dashboard:admin:coupon-list")
    success_message = "کد تخفیف با موفقیت ایجاد شد"

dashboard/admin/views/member.py
from django.views.generic import UpdateView, ListView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import FieldError
from ...permissions import AdminPermissions
from ..forms import *
from accounts.models import User, UserType


class AdminMemberListView(LoginRequiredMixin, AdminPermissions, ListView):
    template_name = "dashboard/admin/members/member-list.html"
    context_object_name = "members"

    paginate_by = 10

    def get_paginate_by(self, queryset):
        return self.request.GET.get("page_size", self.paginate_by)

    def get_queryset(self):
        queryset = (
            User.objects.all()
            .exclude(email=self.request.user.email)
            .exclude(user_type=UserType.superuser.value)
        )
        if search_q := self.request.GET.get("q"):
            queryset = queryset.filter(email__icontains=search_q)
        if order_by := self.request.GET.get("order_by"):
            try:
                queryset = queryset.order_by(order_by)
            except FieldError:
                pass
        return queryset


class AdminMemberEditView(
    LoginRequiredMixin, AdminPermissions, UpdateView, SuccessMessageMixin
):
    template_name = "dashboard/admin/members/member-edit.html"
    form_class = AdminMemberEditForm
    success_message = "کاربر با موفقیت ویرایش شد"

    def get_queryset(self):
        return (
            User.objects.all()
            .exclude(email=self.request.user.email)
            .exclude(user_type=UserType.superuser.value)
        )

    def get_success_url(self):
        return reverse_lazy(
            "dashboard:admin:member-edit", kwargs={"pk": self.get_object().pk}
        )

dashboard/admin/views/order.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from ...permissions import AdminPermissions
from order.models import OrderModel


class OrdersList(LoginRequiredMixin, AdminPermissions, ListView):
    queryset = OrderModel.objects.all()
    template_name = "dashboard/admin/orders/list.html"
    context_object_name = "orders"

    paginate_by = 5

    def get_paginate_by(self, queryset):
        return self.request.GET.get("page_size", self.paginate_by)


class OrderSingle(LoginRequiredMixin, AdminPermissions, DetailView):
    model = OrderModel
    template_name = "dashboard/admin/orders/single.html"
    context_object_name = "order"

dashboard/admin/views/product.py
from django.views.generic import UpdateView, ListView, DeleteView, CreateView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import FieldError
from ...permissions import AdminPermissions
from shop.models import ProductModel, CategoryModel, ProductImageModel
from ..forms import *


class AdminShowProducts(LoginRequiredMixin, AdminPermissions, ListView):
    template_name = "dashboard/admin/products/show-products.html"
    paginate_by = 10

    def get_paginate_by(self, queryset):
        return self.request.GET.get("page_size", self.paginate_by)

    def get_queryset(self):
        queryset = ProductModel.objects.all()
        if search_q := self.request.GET.get("q"):
            queryset = queryset.filter(title__icontains=search_q)
        if category_id := self.request.GET.get("category_id"):
            queryset = queryset.filter(category__id=category_id)
        if order_by := self.request.GET.get("order_by"):
            try:
                queryset = queryset.order_by(order_by)
            except FieldError:
                pass
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_prod"] = self.get_queryset().count()
        context["categories"] = CategoryModel.objects.all()
        return context


class AdminEditProducts(
    LoginRequiredMixin, AdminPermissions, UpdateView, SuccessMessageMixin
):
    queryset = ProductModel.objects.all()
    template_name = "dashboard/admin/products/edit-products.html"
    form_class = AdminEditProductForm

    def get_success_url(self):
        return reverse_lazy(
            "dashboard:admin:edit-prod", kwargs={"pk": self.get_object().pk}
        )


class AdminDeleteProducts(
    LoginRequiredMixin, AdminPermissions, DeleteView, SuccessMessageMixin
):
    queryset = ProductModel.objects.all()
    template_name = "dashboard/admin/products/delete-prod.html"
    success_url = reverse_lazy("dashboard:admin:show-prod")
    success_message = "Product successfuly deleted"


class AdminCreateProducts(
    LoginRequiredMixin, AdminPermissions, CreateView, SuccessMessageMixin
):
    queryset = ProductModel.objects.all()
    template_name = "dashboard/admin/products/create-product.html"
    form_class = AdminEditProductForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["image_form"] = ProductImageForm(
                self.request.POST, self.request.FILES
            )
        else:
            context["image_form"] = ProductImageForm()
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        image_form = ProductImageForm(self.request.POST, self.request.FILES)
        if image_form.is_valid():
            product = form.save()
            images = self.request.FILES.getlist("images")
            for image in images:
                ProductImageModel.objects.create(product=product, image=image)
            return redirect(reverse_lazy("dashboard:admin:show-prod"))
        else:
            return self.form_invalid(form)

dashboard/admin/views/profile.py
from django.views.generic import TemplateView, UpdateView
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from ...permissions import AdminPermissions
from ..forms import *
from accounts.models import User, Profile


class AdminDashboard(LoginRequiredMixin, AdminPermissions, TemplateView):
    template_name = "dashboard/admin/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_info"] = User.objects.get(pk=self.request.user.id)
        return context


class ChangePassView(
    LoginRequiredMixin,
    AdminPermissions,
    SuccessMessageMixin,
    PasswordChangeView,
):
    template_name = "dashboard/admin/profile/change-pass.html"
    form_class = ChangePassForm
    success_url = reverse_lazy("dashboard:admin:change-pass")
    success_message = "Password changed successfully"


class ProfileView(
    LoginRequiredMixin, AdminPermissions, UpdateView, SuccessMessageMixin
):
    template_name = "dashboard/admin/profile/profile.html"
    form_class = ProfileForm
    success_url = reverse_lazy("dashboard:admin:profile")
    success_message = "Profile changed successfully"

    def get_object(self, queryset=None):
        return Profile.objects.get(user=self.request.user)

dashboard/admin/views/ticket.py
from django.views.generic import ListView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import FieldError
from ...permissions import AdminPermissions
from ..forms import *
from ...models import TicketModel


class AdminTicketListView(LoginRequiredMixin, AdminPermissions, ListView):
    template_name = "dashboard/admin/tickets/ticket-list.html"
    context_object_name = "tickets"

    paginate_by = 10

    def get_paginate_by(self, queryset):
        return self.request.GET.get("page_size", self.paginate_by)

    def get_queryset(self):
        queryset = TicketModel.objects.all()
        if search_q := self.request.GET.get("q"):
            queryset = queryset.filter(description__icontains=search_q)
        if order_by := self.request.GET.get("order_by"):
            try:
                queryset = queryset.order_by(order_by)
            except FieldError:
                pass
        return queryset


class AdminTicketDetailView(LoginRequiredMixin, AdminPermissions, DetailView):
    model = TicketModel
    template_name = "dashboard/admin/tickets/ticket-detail.html"
    context_object_name = "ticket"


class AdminTicketDeleteView(
    LoginRequiredMixin, AdminPermissions, DeleteView, SuccessMessageMixin
):
    queryset = TicketModel.objects.all()
    template_name = "dashboard/admin/tickets/ticket-delete.html"
    success_url = reverse_lazy("dashboard:admin:ticket-list")
    success_message = "تیکت با موفقیت حذف شد"

dashboard/customer/views/address.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from ...permissions import CustomerPermissions
from ..forms import *
from order.models import AddressModel


class AddressesView(LoginRequiredMixin, CustomerPermissions, ListView):
    template_name = "dashboard/customer/orders/addresses.html"
    context_object_name = "addresses"

    def get_queryset(self):
        queryset = AddressModel.objects.filter(user=self.request.user)
        return queryset


class AddAddressesView(
    LoginRequiredMixin, CustomerPermissions, CreateView, SuccessMessageMixin
):
    form_class = AddAddressesForm
    template_name = "dashboard/customer/orders/add-addresses.html"
    success_message = "آدرس با موفقیت ذخیره شد"
    success_url = reverse_lazy("dashboard:customer:addresses")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ChangeAddressesView(
    LoginRequiredMixin, CustomerPermissions, UpdateView
):
    template_name = "dashboard/customer/orders/change-addresses.html"
    form_class = AddAddressesForm
    success_url = reverse_lazy("dashboard:customer:addresses")
    success_message = "Profile changed successfully"

    def get_object(self, queryset=None):
        return AddressModel.objects.get(
            pk=self.kwargs.get("pk"), user=self.request.user
        )

dashboard/customer/views/order.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from ...permissions import CustomerPermissions
from ..forms import *
from order.models import OrderModel


class OrderView(LoginRequiredMixin, CustomerPermissions, ListView):
    template_name = "dashboard/customer/orders/orders.html"
    context_object_name = "orders"

    def get_queryset(self):
        queryset = OrderModel.objects.filter(user=self.request.user)
        return queryset

    paginate_by = 9

    def get_paginate_by(self, queryset):
        return self.request.GET.get("page_size", self.paginate_by)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["orders_counter"] = len(self.get_queryset())
        return context


class OrderDetailView(LoginRequiredMixin, CustomerPermissions, DetailView):
    model = OrderModel
    template_name = "dashboard/customer/orders/order-detail.html"
    context_object_name = "order"


class OrderInvoiceView(LoginRequiredMixin, DetailView):
    model = OrderModel
    template_name = "dashboard/customer/orders/order-invoice.html"
    context_object_name = "order"

templates/dashboard/customer/home.html
{% extends 'dashboard/customer/base.html' %}
{% load static %}

{% block content %}
<!-- Card -->
<div class="card">
    <!-- Header -->
    <div class="card-header border-bottom">
        <h5 class="card-header-title">اطلاعات من</h5>
    </div>
    <!-- End Header -->

    <div class="container mt-5">
        <!-- <h1 class="mb-4 text-center">اطلاعات من</h1> -->
        <div class="row">
            <div class="col-md-6 mb-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">ایمیل</h5>
                        <p class="card-text">{{user_info.email}}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">نام و نام خانوادگی</h5>
                        <p class="card-text">{{user_info.user_profile.get_fullname}}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">شماره تلفن</h5>
                        <p class="card-text">{{user_info.user_profile.phone_number}}</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">نوع کاربر</h5>
                        <p class="card-text">مشتری</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Card -->
{% endblock %}

templates/dashboard/customer/sidebar.html
{% load static %}
<!-- Navbar -->
 <div class="navbar-expand-lg navbar-light">
    <div id="sidebarNav" class="collapse navbar-collapse navbar-vertical">
      <!-- Card -->
      <div class="card flex-grow-1 mb-5">
        <div class="card-body">
          <!-- Avatar -->
          <div class="d-none d-lg-block text-center mb-5">
            <form action="{% url 'dashboard:profile-edit' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="avatar avatar-xxl avatar-circle mb-3">
                  <input type="file" accept=".jpg, .jpeg" style="display:none;" id="fileInput" name="avatar">
                  <img class="avatar-img" src="{{request.user.user_profile.avatar.url}}" alt="Image Description" onclick="document.getElementById('fileInput').click();" />
              </div>
              
              
              <h4 class="card-title mb-0">{{request.user.user_profile.get_fullname}}</h4>
              <p class="card-text small">{{request.user.email}}</p>
              <br>
              <button type="submit" class="btn btn-primary">ذخیره پروفایل</button>
            </form>
          </div>
          <!-- End Avatar -->

          <!-- Nav -->
          <span class="text-cap">حساب</span>

          <!-- List -->
          <ul class="nav nav-sm nav-tabs nav-vertical mb-4">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:customer:home' %}">
                <i class="bi-person-badge nav-icon"></i>داشبورد
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:customer:change-pass' %}">
                <i class="bi-shield-shaded nav-icon"></i> امنیت
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:customer:profile' %}">
                <i class="bi-sliders nav-icon"></i> تنظیمات پروفایل
              </a>
            </li>
          </ul>
          <!-- End List -->

          <span class="text-cap">خريد كردن</span>

          <!-- List -->
          <ul class="nav nav-sm nav-tabs nav-vertical mb-4">
            <li class="nav-item">
              <a class="nav-link " href="{% url 'dashboard:customer:order-list' %}">
                <i class="bi-basket nav-icon"></i> سفارشات شما
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'dashboard:customer:wishlist' %}">
                <i class="bi-heart nav-icon"></i>لیست علایق
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link " href="{% url 'dashboard:customer:addresses' %}">
                <i class="bi-geo-alt nav-icon"></i> نشانی
              </a>
            </li>

          </ul>
          <!-- End List -->


          <!-- End List -->

          <div class="d-lg-none">
            <div class="dropdown-divider"></div>

            <!-- List -->
            <ul class="nav nav-sm nav-tabs nav-vertical">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <i class="bi-box-arrow-right nav-icon"></i> خروج
                </a>
              </li>
            </ul>
            <!-- End List -->
          </div>
          <!-- End Nav -->
        </div>
      </div>
      <!-- End Card -->
    </div>
  </div>
  <!-- End Navbar -->