cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.CartView.as_view(), name="cart-summery"),
    path("session/add-prod/", views.AddProdView.as_view(), name="add-prod"),
    path("session/del-prod/", views.DelProdView.as_view(), name="del-prod"),
    path("session/clear/", views.ClearView.as_view(), name="clear"),
    path(
        "session/change-prod-quantity/",
        views.ChangeProdQuantityView.as_view(),
        name="change-prod-quantity",
    ),
]

core/urls.py
from itertools import product
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
from shop.sitemaps import ProductSitemap

sitemaps = {"static": StaticViewSitemap, "products": ProductSitemap}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("website.urls")),
    path("accounts/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("cart/", include("cart.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
    path("review/", include("review.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

handler404 = "core.error_views.error_404"

if settings.DEBUG:
    import debug_toolbar
    from rest_framework import permissions
    from drf_yasg.views import get_schema_view
    from drf_yasg import openapi

    schema_view = get_schema_view(
        openapi.Info(
            title="Django Online Shop API",
            default_version="v1",
            description="you can use it by any front end framework like (React, Vue, Angular, ...)",
            terms_of_service="https://www.google.com/policies/terms/",
            contact=openapi.Contact(email="benxfoxy@gmail.com"),
            license=openapi.License(name="MIT License"),
        ),
        public=True,
        permission_classes=(permissions.AllowAny,),
    )

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
        path(
            "swagger<format>/",
            schema_view.without_ui(cache_timeout=0),
            name="schema-json",
        ),
        path(
            "swagger/",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
    ]

    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [
    path("checkout/", views.CheckOutView.as_view(), name="checkout"),
    path("check/", views.CheckView.as_view(), name="check"),
    path("complete/", views.OrderCompleteView.as_view(), name="complete"),
    path("faild/", views.OrderFaildView.as_view(), name="faild"),
]

shop/urls.py
from django.urls import include, path, re_path
from . import views

app_name = "shop"

urlpatterns = [
    path(
        "product/list/grid/",
        views.ShopProductGridListView.as_view(),
        name="list_grid",
    ),
    path("product/list/", views.ShopProductListView.as_view(), name="list"),
    re_path(
        r"product/(?P<slug>[-\w]+)/detail/",
        views.ShopProductDetailView.as_view(),
        name="detail",
    ),
    path(
        "product/add-or-remove-wish/",
        views.AddOrRemoveWish.as_view(),
        name="modify-wish",
    ),
    # Shop API section
    path("api/v1/", include("shop.api.urls")),
]

order/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from decimal import Decimal


class OrderStatusModel(models.IntegerChoices):
    pending = 1, "Pending Payment"
    success = 2, "Successful"
    failed = 3, "Canceled"



class AddressModel(models.Model):
    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=50)
    address = models.TextField()

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.address


class CouponModel(models.Model):
    code = models.CharField(max_length=100)
    discount_percent = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(100)]
    )
    max_limit_usage = models.IntegerField()
    used_by = models.ManyToManyField("accounts.User", blank=True)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.code

    class Meta:
        ordering = ("-created_date",)


class OrderModel(models.Model):
    user = models.ForeignKey("accounts.User", on_delete=models.PROTECT)
    address = models.ForeignKey(AddressModel, on_delete=models.PROTECT)
    coupon = models.ForeignKey(
        CouponModel, on_delete=models.PROTECT, blank=True, null=True
    )
    status = models.IntegerField(
        choices=OrderStatusModel.choices,
        default=OrderStatusModel.pending.value,
    )
    final_price = models.DecimalField(
        default=0, max_digits=10, decimal_places=0
    )

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user)

    class Meta:
        ordering = ("-created_date",)

    def get_fulladdress(self):
        return f"({self.address.state} - {self.address.city}) {self.address.address}"

    def get_status(self):
        return {
            "id": self.status,
            "title": OrderStatusModel(self.status).name,
            "label": OrderStatusModel(self.status).label,
        }

    def get_totalprice(self):
        if self.coupon:
            discount_rate = Decimal(self.coupon.discount_percent) / Decimal(
                100
            )
            return self.final_price / (Decimal(1) - discount_rate)
        return self.final_price


class OrderItemsModel(models.Model):
    order = models.ForeignKey(
        OrderModel, on_delete=models.CASCADE, related_name="order_items"
    )
    product = models.ForeignKey("shop.ProductModel", on_delete=models.PROTECT)
    quantity = models.IntegerField(default=0)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=0)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.order.user} - {self.product.title}"

order/forms.py
from django import forms
from order.models import AddressModel, CouponModel


class CheckOutForm(forms.Form):
    address_id = forms.IntegerField(required=True)
    coupon_code = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super(CheckOutForm, self).__init__(*args, **kwargs)

    def clean_address_id(self):
        address_id = self.cleaned_data.get("address_id")
        try:
            address = AddressModel.objects.get(
                id=address_id, user=self.request.user
            )
        except AddressModel.DoesNotExist:
            raise forms.ValidationError("آدرس با اطلاعات کاربر تطابق ندارد")

        return address

    def clean_coupon_code(self):
        coupon_code = self.cleaned_data.get("coupon_code")
        coupon = None
        if coupon_code == "":
            return coupon

        try:
            coupon = CouponModel.objects.get(code=coupon_code)
        except CouponModel.DoesNotExist:
            raise forms.ValidationError("کد وارد شده اشتباه است")

        if coupon:
            if self.request.user in coupon.used_by.all():
                raise forms.ValidationError(
                    "این کد توسط شما یک بار استفاده شده است"
                )
            if coupon.max_limit_usage == 0:
                raise forms.ValidationError("کد دیگر فاقد ارزش است")
        return coupon

dashboard/admin/views/order.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from ...permissions import AdminPermissions
from order.models import OrderModel


class OrdersList(LoginRequiredMixin, AdminPermissions, ListView):
    queryset = OrderModel.objects.all()
    template_name = "dashboard/admin/orders/list.html"
    context_object_name = "orders"

    paginate_by = 5

    def get_paginate_by(self, queryset):
        return self.request.GET.get("page_size", self.paginate_by)


class OrderSingle(LoginRequiredMixin, AdminPermissions, DetailView):
    model = OrderModel
    template_name = "dashboard/admin/orders/single.html"
    context_object_name = "order"

dashboard/customer/views/order.py
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from ...permissions import CustomerPermissions
from ..forms import *
from order.models import OrderModel


class OrderView(LoginRequiredMixin, CustomerPermissions, ListView):
    template_name = "dashboard/customer/orders/orders.html"
    context_object_name = "orders"

    def get_queryset(self):
        queryset = OrderModel.objects.filter(user=self.request.user)
        return queryset

    paginate_by = 9

    def get_paginate_by(self, queryset):
        return self.request.GET.get("page_size", self.paginate_by)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["orders_counter"] = len(self.get_queryset())
        return context


class OrderDetailView(LoginRequiredMixin, CustomerPermissions, DetailView):
    model = OrderModel
    template_name = "dashboard/customer/orders/order-detail.html"
    context_object_name = "order"


class OrderInvoiceView(LoginRequiredMixin, DetailView):
    model = OrderModel
    template_name = "dashboard/customer/orders/order-invoice.html"
    context_object_name = "order"

order/views.py
from django.views.generic import TemplateView, FormView, View
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.http import JsonResponse
from .models import AddressModel, OrderModel, CouponModel, OrderItemsModel
from cart.models import CartModel
from .forms import CheckOutForm
from cart.cart import CartSession
from payment.zarinpal_client import ZarinPalSandbox
from payment.models import PaymentModel


class CheckOutView(LoginRequiredMixin, SuccessMessageMixin, FormView):
    template_name = "order/checkout.html"
    form_class = CheckOutForm
    success_url = reverse_lazy("order:complete")
    success_message = "سفارش با موفقیت ثبت شد"

    def get_form_kwargs(self):
        kwargs = super(CheckOutView, self).get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def form_valid(self, form):
        user = self.request.user
        cart = CartModel.objects.get(user=user)
        address = form.cleaned_data["address_id"]
        coupon = form.cleaned_data["coupon_code"]
        total_price = cart.calculate_total_price()
        tax_price = total_price / 100 * 9
        final_price = total_price + tax_price
        order = self.create_order(user, address, coupon, final_price)

        self.merge_items(cart, order)
        order.save()
        self.clear_cart(cart)

        return redirect(self.payment_method_url(order))

    def create_order(self, user, address, coupon, final_price):
        if coupon:
            self.update_coupon(user, coupon)
            discounted_price = final_price / 100 * coupon.discount_percent
            final_price -= discounted_price
        return OrderModel.objects.create(
            user=user, address=address, coupon=coupon, final_price=final_price
        )

    def merge_items(self, cart, order):
        for prod in cart.cart_items.all():
            OrderItemsModel.objects.create(
                order=order,
                product=prod.product,
                quantity=prod.quantity,
                price=prod.product.offer(),
            )

    def update_coupon(self, user, coupon):
        if coupon:
            coupon.max_limit_usage -= 1
            coupon.used_by.add(user)
            coupon.save()

    def payment_method_url(self, order):
        zarinpal = ZarinPalSandbox()
        response = zarinpal.payment_request(order.final_price)
        PaymentModel.objects.create(
            authority=response["data"]["authority"],
            amount=order.final_price,
            order=order,
        )
        return zarinpal.generate_payment_url(response["data"]["authority"])

    def clear_cart(self, cart):
        CartSession(self.request.session).clear()
        cart.delete()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = CartModel.objects.get(user=self.request.user)
        total_price = cart.calculate_total_price()
        tax_price = total_price / 100 * 9
        final_price = total_price + tax_price
        context["addresses"] = AddressModel.objects.filter(
            user=self.request.user
        )
        context["total_price"] = total_price
        context["tax_price"] = tax_price
        context["final_price"] = final_price

        return context


class CheckView(View):
    def post(self, request, *args, **kwargs):
        coupon_code = request.POST.get("coupon_code")
        message = "Coupon successfully applied"
        try:
            coupon = CouponModel.objects.get(code=coupon_code)
        except CouponModel.DoesNotExist:
            return JsonResponse({"message": "Coupon code not found"})

        else:
            if self.request.user in coupon.used_by.all():
                message = "You have already used this coupon"
            if coupon.max_limit_usage == 0:
                message = "This coupon is no longer valid"
            else:
                cart = CartModel.objects.get(user=self.request.user)

                total_price = cart.calculate_total_price() + (
                    cart.calculate_total_price() / 100 * 9
                )

                discounted_price = total_price / 100 * coupon.discount_percent
                print(discounted_price)

        return JsonResponse(
            {"discounted_price": discounted_price, "message": message}
        )


class OrderCompleteView(TemplateView):
    template_name = "order/complete.html"


class OrderFaildView(TemplateView):
    template_name = "order/faild.html"

templates/order/checkout.html
{% extends "base.html" %}
{% load static %}
<title>{% block title %}Yoogi | checkout {% endblock title %}</title>  
{% load humanize %}
{% block content %}
    <!-- Content -->
    <div class="container content-space-1 content-space-lg-2">
        <div class="row">
          <div class="col-lg-8 mb-7 mb-lg-0">
            <h4 class="mb-3">Select Address</h4>
             <!-- Form -->
          <form action="." method="post" id="checkout">
            {% csrf_token %}
              <hr class="my-4">
  
              <div class="d-grid gap-2">
                
                {% for address in addresses %}
                <!-- Check -->
                <div class="form-check">
                  <input type="radio" class="form-check-input" name="address_id" value="{{address.id}}" required checked>
                  <label class="form-check-label" for="address">{{address.state}} - {{address.city}} - {{address.address}} - {{address.zip_code}}</label>
                </div>
                <!-- End Check -->
                {% endfor %}
                <div>
                  <a href="{% url 'dashboard:customer:addresses' %}">Manage Addresses</a>
                </div>
              </div>
  
              <hr class="my-4">
  
              <div class="row align-items-center">
  
                <div class="col-sm text-center text-sm-start">
                  <a class="link" href="{% url 'cart:cart-summery' %}">
                    <i class="bi-chevron-left small ms-1"></i> Back to Cart
                  </a>
                </div>
                <!-- End Col -->
              </div>
              <!-- End Row -->
            </form>
            <!-- End Form -->
          </div>
          <!-- End Col -->
  
          <div class="col-lg-4">
            <div class="ps-lg-4">
              <!-- Card -->
              <div class="card card-sm shadow-sm mb-4">
                <div class="card-body">
                  <div class="border-bottom pb-4 mb-4">
                    <h3 class="card-header-title">Order Summary</h3>
                  </div>
                    <div class="input-group border-bottom pb-4 mb-3 ">
                      <input form="checkout" type="text" class="form-control text-center" name="coupon_code" placeholder="Discount Code"
                      aria-label="Discount Code" id="coupon-check">
                      <button class="btn btn-primary" type="button" onclick="validateCoupon()">Check</button>
                    </div>
  
                    <div class="border-bottom pb-4 mb-4">
                    
  
                    <div class="d-grid gap-3 mb-4">
                      <!-- End Row -->
  
                      <dl class="row">
                        <dt class="col-sm-6">Price Calculation</dt>
                        <dd class="col-sm-10 text-sm-end mb-0" id="priceDetails">
                          <span>Total Price: {{total_price|intcomma}} ksh</span>
                          <br>
                          <span>9% Tax: {{tax_price|intcomma}} ksh</span>
                          <br>
                        </dd>
                      </dl>
                      <!-- End Row -->
                      <dl class="row">
                        <dt class="col-sm-6">Grand Total</dt>
                        <dd class="col-sm-10 text-sm-end mb-0">
                          <span id="final-price">{{final_price|intcomma}}</span> ksh
                        </dd>
                      </dl>
                      <!-- End Row -->
                    </div>
  
                    <div class="d-grid">
                      <button form="checkout" type="submit" class="btn btn-primary btn-lg">Finalize Order</button>
                    </div>
                </div>
                <!-- End Card -->
              </div>
  
              <!-- Media -->
              <div class="d-flex align-items-center">
                <div class="flex-shrink-0">
                  <div class="svg-icon svg-icon-sm text-primary">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" clip-rule="evenodd"
                        d="M22.1671 18.1421C22.4827 18.4577 23.0222 18.2331 23.0206 17.7868L23.0039 13.1053V5.52632C23.0039 4.13107 21.8729 3 20.4776 3H8.68815C7.2929 3 6.16183 4.13107 6.16183 5.52632V9H13C14.6568 9 16 10.3431 16 12V15.6316H19.6565L22.1671 18.1421Z"
                        fill="#035A4B" />
                      <path opacity="0.3" fill-rule="evenodd" clip-rule="evenodd"
                        d="M1.98508 18V13C1.98508 11.8954 2.88051 11 3.98508 11H11.9851C13.0896 11 13.9851 11.8954 13.9851 13V18C13.9851 19.1046 13.0896 20 11.9851 20H4.10081L2.85695 21.1905C2.53895 21.4949 2.01123 21.2695 2.01123 20.8293V18.3243C1.99402 18.2187 1.98508 18.1104 1.98508 18ZM5.99999 14.5C5.99999 14.2239 6.22385 14 6.49999 14H11.5C11.7761 14 12 14.2239 12 14.5C12 14.7761 11.7761 15 11.5 15H6.49999C6.22385 15 5.99999 14.7761 5.99999 14.5ZM9.49999 16C9.22385 16 8.99999 16.2239 8.99999 16.5C8.99999 16.7761 9.22385 17 9.49999 17H11.5C11.7761 17 12 16.7761 12 16.5C12 16.2239 11.7761 16 11.5 16H9.49999Z"
                        fill="#035A4B" />
                    </svg>
  
                  </div>
                </div>
                <div class="flex-grow-1 ms-2">
                  <span class="small me-1">Need Support?</span>
                  <a class="link small" href="#">Submit Ticket</a>
                </div>
              </div>
              <!-- End Media -->
            </div>
          </div>
          <!-- End Col -->
        </div>
        <!-- End Row -->
      </div>
      <!-- End Content -->
{% endblock content %}


{% block extera-js %}
<script>
  function discountPrice(discounted_price){
      // Create a new <span> element with jQuery
      var discountSpan = $('<span>').text('مقدار تخفیف : ' + discounted_price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + ' تومان');

      // Find the target <dd> element
      var priceDetails = $('#priceDetails');

      // Append the new <span> element to the <dd> element
      priceDetails.append(discountSpan);
      // $('#final-price').val() -= discounted_price;
      var newPrice = parseInt($('#final-price').text().replace(/,/g, "")) - discounted_price;
      $('#final-price').text(newPrice.toLocaleString())


    }

  function validateCoupon() {
    $.ajax({
    type: "POST",
    url: "{% url 'order:check' %}",
    data: {
      'coupon_code': $('#coupon-check').val(),
      csrfmiddlewaretoken: '{{ csrf_token }}',
    },
    success: function(response){
      Toastify({
                text:response.message,
                className: `{{ message.tags }}`,
                style: {
                  background: "#4CAF50",
                }
              }).showToast();
      discountPrice(response.discounted_price)
    },
    error: function(jqXHR,textStatus,errorThrown) {
      console.log(response)
    }
  });
  }
</script>
{% endblock extera-js %}

templates/order/complete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
      <!-- Content -->
      <div class="container content-space-2 content-space-lg-3">
        <div class="w-md-75 w-lg-50 text-center mx-md-auto">
          <div class="mb-5">
            <img class="img-fluid" src="{% static 'svg/illustrations/oc-hi-five.svg' %}" alt="Image Description" style="width: 15rem;">
          </div>
  
          <div class="mb-5">
            <h1 class="h2">Your order is complete!</h1>
            <p>Thank you for your order! Your order is being processed and will be completed within 3 to 6 hours. You will receive a confirmation email once your order is completed.</p>
          </div>
  
          <a class="btn btn-primary btn-transition rounded-pill px-6" href="{% url 'shop:list_grid' %}">Continue Shopping</a>
        </div>
      </div>
      <!-- End Content -->
{% endblock content %}

templates/order/faild.html
{% extends "base.html" %}
{% load static %}

{% block content %}
      <!-- Content -->
      <div class="container content-space-2 content-space-lg-3">
        <div class="w-md-75 w-lg-50 text-center mx-md-auto">
          <div class="mb-5">
            <img class="img-fluid" src="{% static 'img/credit-card.png' %}" alt="Image Description" style="width: 15rem;">
          </div>
  
          <div class="mb-5">
            <h1 class="h2">Payment was not successful!</h1>
          </div>
  
          <a class="btn btn-primary btn-transition rounded-pill px-6" href="{% url 'shop:list_grid' %}">Continue Shopping</a>
        </div>
      </div>
      <!-- End Content -->
{% endblock content %}